// Quasi-steady internal ballistics: at every web step, mass generated by the burning surface equals mass
// choked out of the throat:  ρ·Ab·a·Pcⁿ = Pc·At/c*   ⇒   Pc = (a·ρ·c*·Kn)^(1/(1−n)),  Kn = Ab/At.
import { G0, thrustCoef, ambient } from '../shared/nozzle';
import type { BurnResult } from './types';

export interface Propellant {
  name: string; rho: number; rRef: number; pRef: number; n: number; cstar: number; g: number; sigma: number; Tc: number;
  flame: number[]; core: number[]; disk: number[]; smoke: number[]; color: number; note: string;
}

// burn rate r = a·Pcⁿ, given here as rRef at pRef (a = rRef / pRefⁿ)
export const PROPS: Record<string, Propellant> = {
  apcp: { name: 'APCP', rho: 1770, rRef: 0.0075, pRef: 6.9e6, n: 0.35, cstar: 1540, g: 1.18, sigma: 0.0018, Tc: 3400, color: 0xb8ab93,
    flame: [2.2, 1.8, 1.3], core: [3, 2.8, 2.5], disk: [2.4, 2.1, 1.8], smoke: [0.86, 0.86, 0.85, 0.55],
    note: 'Ammonium perchlorate composite: AP oxidiser crystals and aluminium powder held in a rubbery HTPB binder. It has the texture of a pencil eraser. The burning aluminium makes the blinding white flame and the thick white smoke of aluminium oxide.' },
  pban: { name: 'PBAN', rho: 1715, rRef: 0.00935, pRef: 4.31e6, n: 0.35, cstar: 1510, g: 1.18, sigma: 0.0017, Tc: 3300, color: 0xa99e8c,
    flame: [2.3, 1.7, 1.1], core: [3, 2.6, 2.1], disk: [2.4, 1.9, 1.4], smoke: [0.8, 0.79, 0.77, 0.6],
    note: 'The Space Shuttle booster propellant: AP and aluminium in a PBAN binder. It is cheap, well understood and cast by the tonne, and each Shuttle booster held about 500 t of it.' },
  knsb: { name: 'KNSB', rho: 1800, rRef: 0.006, pRef: 5e6, n: 0.32, cstar: 910, g: 1.13, sigma: 0.0012, Tc: 1600, color: 0xd8b77a,
    flame: [2.2, 0.9, 0.7], core: [2.6, 1.6, 1.2], disk: [2.2, 1.2, 1.0], smoke: [0.9, 0.9, 0.9, 0.7],
    note: '“Rocket candy”: potassium nitrate and sorbitol, cast like hard caramel. It is safe enough for amateurs but has a low c*, so its Isp is only about 60 % of APCP. The flame is pinkish from the potassium.' },
};

export interface Sim {
  t: Float32Array; pc: Float32Array; F: Float32Array; w: Float32Array; kn: Float32Array; r: Float32Array; mdot: Float32Array;
  tb: number; tEnd: number; It: number; mprop: number; pcMax: number; isp: number; At: number; eps: number;
  cls: string; shape: 'progressive' | 'neutral' | 'regressive'; chuffed: boolean;
}

export function simulate(res: BurnResult, prop: Propellant, rt: number, re: number, o: { tempC: number; altKm: number }): Sim {
  const At = Math.PI * rt * rt, eps = (re / rt) ** 2, pa = ambient(o.altKm);
  const a = (prop.rRef / Math.pow(prop.pRef, prop.n)) * Math.exp(prop.sigma * (o.tempC - 21)); // hotter grain burns faster
  const nb = res.ab.length, ex = 1 / (1 - prop.n);
  const T: number[] = [], PC: number[] = [], FF: number[] = [], W: number[] = [], KN: number[] = [], R: number[] = [], MD: number[] = [];
  const push = (t: number, pc: number, w: number, kn: number, r: number) => {
    const cf = pc > pa * 1.05 ? thrustCoef(pc, pa, eps, prop.g).CF : 0;
    T.push(t); PC.push(pc); FF.push(cf * pc * At); W.push(w); KN.push(kn); R.push(r); MD.push((pc * At) / prop.cstar);
  };
  const ramp = 0.08; // igniter + fill: cosmetic ramp, the steady model has none
  let t = 0, w = 0, chuffed = false;
  push(0, pa, 0, 0, 0);
  for (let k = 0; k < nb; k++) {
    const Ab = res.ab[k], kn = Ab / At;
    const pc = Math.pow(a * prop.rho * prop.cstar * kn, ex);
    if (pc < 2 * pa || !isFinite(pc)) { if (k < nb * 0.9) chuffed = true; continue; } // too little area to sustain burning
    const r = a * Math.pow(pc, prop.n);
    t += res.dw / r; w += res.dw;
    push(t + ramp, pc, w, kn, r);
  }
  const tb = t + ramp;
  // blow-down after the last propellant is gone: τ = V / (At·c*·Γ²)
  const Γ2 = prop.g * Math.pow(2 / (prop.g + 1), (prop.g + 1) / (prop.g - 1));
  const tau = Math.max(0.05, (res.volume * 1.15) / (At * prop.cstar * Γ2));
  const pcB = PC[PC.length - 1];
  for (let i = 1; i <= 12; i++) { const dt = (i / 12) * 5 * tau; push(tb + dt, Math.max(pa, pcB * Math.exp(-dt / tau)), w, 0, 0); }
  let It = 0, pcMax = 0;
  for (let i = 1; i < T.length; i++) { It += 0.5 * (FF[i] + FF[i - 1]) * (T[i] - T[i - 1]); pcMax = Math.max(pcMax, PC[i]); }
  const mprop = res.volume * prop.rho;
  const avg = (a: number, z: number) => { let s = 0; for (let k = Math.floor(nb * a); k < Math.floor(nb * z); k++) s += res.ab[k]; return s / (Math.floor(nb * z) - Math.floor(nb * a)); };
  const ab0 = avg(0.02, 0.15), ab1 = avg(0.7, 0.85);
  const cls = It < 1.25 ? '¼A' : String.fromCharCode(65 + Math.max(0, Math.ceil(Math.log2(It / 2.5))));
  return {
    t: Float32Array.from(T), pc: Float32Array.from(PC), F: Float32Array.from(FF), w: Float32Array.from(W), kn: Float32Array.from(KN), r: Float32Array.from(R), mdot: Float32Array.from(MD),
    tb, tEnd: T[T.length - 1], It, mprop, pcMax, isp: It / (mprop * G0), At, eps, cls, chuffed,
    shape: ab1 > ab0 * 1.15 ? 'progressive' : ab1 < ab0 * 0.85 ? 'regressive' : 'neutral',
  };
}

/** Linear interpolation of a sim channel at time t. */
export function at(s: Sim, ch: Float32Array, t: number): number {
  const T = s.t;
  if (t <= T[0]) return ch[0];
  if (t >= T[T.length - 1]) return ch[ch.length - 1];
  let lo = 0, hi = T.length - 1;
  while (hi - lo > 1) { const m = (lo + hi) >> 1; if (T[m] > t) hi = m; else lo = m; }
  const f = (t - T[lo]) / (T[hi] - T[lo] || 1);
  return ch[lo] + (ch[hi] - ch[lo]) * f;
}
